import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Composant1 from "@/composants/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mon porte folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Composant1 />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.title}>
        <h1>About <font color="#227B97">Me</font></h1>
        </div>
        <br/>
        <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at lectus non nunc pulvinar vulputate at nec lectus. Donec at mauris tempor, lobortis lorem eget, hendrerit ipsum. Nulla ut luctus urna. Nulla facilisi. Aenean orci tortor, ornare a suscipit eget, tincidunt vel ligula. In nec lectus quis velit pretium fringilla. Aenean venenatis viverra volutpat. Phasellus convallis scelerisque auctor. Curabitur tempor fermentum fringilla. Donec malesuada libero orci, at porta quam eleifend eu. Cras fermentum pellentesque pharetra. Suspendisse consequat enim scelerisque ornare tincidunt. Suspendisse potenti. Cras commodo, mauris vel sollicitudin molestie, enim massa fermentum enim, ac feugiat orci risus eget libero. Aenean eleifend lorem convallis lectus dignissim, a malesuada sapien scelerisque. Sed in ornare lorem, in placerat felis.

Nulla at aliquam arcu. Curabitur gravida risus id elit mattis, eget lobortis metus aliquet. Nam ultricies venenatis tortor quis rhoncus. Donec non magna at neque aliquam rutrum ac sed est. Suspendisse vel augue vel orci ornare convallis. Vestibulum semper sit amet augue et commodo. Proin iaculis consectetur ligula sit amet egestas. Pellentesque vel tortor metus. Phasellus faucibus nulla non nisi condimentum lacinia. Praesent vitae lacus aliquam, sagittis tortor quis, pretium mauris. Pellentesque euismod sem non lectus euismod, nec aliquam eros ultrices.</h2>
      </main>
      </>
  );
}