import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Composant1 from "@/composants/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mon porte folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Composant1 />
      <main className={`${styles.main} ${inter.className}`}>
      <div className={styles.contacteznous}>
        <h1>Contactez-nous</h1>
        <form action="/page-traitement-donnees" method="post">
        <div>
        <label for="nom">Votre nom</label>
        <input type="text" id="nom" name="nom" placeholder="Martin" required />
        </div>
        <div>
        <label for="email">Votre e-mail</label>
        <input type="email" id="email" name="email" placeholder="monadresse@mail.com" required />
        </div>
        <div>
        <label for="sujet">Quel est le sujet de votre message ?</label>
        <select name="sujet" id="sujet" required>
        <option value="" disabled selected hidden>Choisissez le sujet de votre message</option>
        <option value="probleme-compte">Problème avec mon compte</option>
        <option value="question-produit">Question à propos d'un produit</option>
        <option value="suivi-commande">Suivi de ma commande</option>
        <option value="autre">Autre...</option>
        </select>
        </div>
        <div>
        <label for="message">Votre message</label>
        <textarea id="message" name="message" placeholder="Bonjour, je vous contacte car...." required></textarea>
        </div>
        <div>
        <button type="submit">Envoyer mon message</button>
        </div>
        </form>
        </div>
      </main>
      </>
  );
}