import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Composant1 from "@/composants/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mon porte folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Composant1 />
      <main className={`${styles.main} ${inter.className}`}>
        <div>
        <div className={styles.title}>
        <h1>Hi! <br/> I'm <font color="#227B97">Maxime</font> <br/> Web developper</h1>
        <Image 
                
                src="/logo-2.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={200}
                height={200}
                priority
              />
        </div>
        
          <button className={styles.card}>Contact</button>
        </div>
      </main>
    </>
  );
}
