import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Composant1 from "@/composants/navbar";
import Todolist from "@/composants/Todolist"


const inter = Inter({ subsets: ["latin"] });

export default function App() {
  return (
    <>
      <Head>
        <title>Mon porte folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Composant1 />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.title}>
        <Todolist />
        </div>
      </main>
    </>
  );
}
